apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedding-service
  namespace: videocopilot
  labels:
    app: embedding-service
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: embedding-service
  template:
    metadata:
      labels:
        app: embedding-service
        component: backend
    spec:
      containers:
      - name: embedding-service
        image: ghcr.io/jaidityayadav/VideoCopilot/embedding-service:latest
        ports:
        - containerPort: 8001
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: videocopilot-secrets
              key: database-url
        - name: PINECONE_API_KEY
          valueFrom:
            secretKeyRef:
              name: videocopilot-secrets
              key: pinecone-api-key
        - name: PINECONE_INDEX_NAME
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: pinecone-index-name
        - name: PINECONE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: pinecone-environment
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: embedding-host
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: embedding-port
        - name: WORKERS
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: embedding-workers
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: embedding-log-level
        - name: MODEL_NAME
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: model-name
        - name: MAX_SEQUENCE_LENGTH
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: max-sequence-length
        - name: BATCH_SIZE
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: batch-size
        volumeMounts:
        - name: models-storage
          mountPath: /app/models
        - name: logs-storage
          mountPath: /app/logs
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: models-storage
        persistentVolumeClaim:
          claimName: embedding-models-pvc
      - name: logs-storage
        persistentVolumeClaim:
          claimName: embedding-logs-pvc
      imagePullSecrets:
      - name: docker-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: embedding-service
  namespace: videocopilot
  labels:
    app: embedding-service
    component: backend
spec:
  selector:
    app: embedding-service
  ports:
  - port: 8000
    targetPort: 8001
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: embedding-models-pvc
  namespace: videocopilot
  labels:
    app: embedding-service
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: embedding-logs-pvc
  namespace: videocopilot
  labels:
    app: embedding-service
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path