apiVersion: apps/v1
kind: Deployment
metadata:
  name: intelligence-service
  namespace: videocopilot
  labels:
    app: intelligence-service
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: intelligence-service
  template:
    metadata:
      labels:
        app: intelligence-service
        component: backend
    spec:
      containers:
      - name: intelligence-service
        image: ghcr.io/jaidityayadav/VideoCopilot/intelligence-service:latest
        ports:
        - containerPort: 8002
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: videocopilot-secrets
              key: database-url
        - name: PINECONE_API_KEY
          valueFrom:
            secretKeyRef:
              name: videocopilot-secrets
              key: pinecone-api-key
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: videocopilot-secrets
              key: groq-api-key
        - name: PINECONE_INDEX_NAME
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: pinecone-index-name
        - name: PINECONE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: pinecone-environment
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: intelligence-host
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: intelligence-port
        - name: WORKERS
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: intelligence-workers
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: intelligence-log-level
        - name: LLM_MODEL
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: llm-model
        - name: LLM_TEMPERATURE
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: llm-temperature
        - name: LLM_MAX_TOKENS
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: llm-max-tokens
        - name: RETRIEVAL_K
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: retrieval-k
        - name: SIMILARITY_THRESHOLD
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: similarity-threshold
        - name: EMBEDDING_SERVICE_URL
          value: "http://embedding-service:8001"
        volumeMounts:
        - name: models-storage
          mountPath: /app/models
        - name: logs-storage
          mountPath: /app/logs
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: models-storage
        persistentVolumeClaim:
          claimName: intelligence-models-pvc
      - name: logs-storage
        persistentVolumeClaim:
          claimName: intelligence-logs-pvc
      imagePullSecrets:
      - name: docker-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: intelligence-service
  namespace: videocopilot
  labels:
    app: intelligence-service
    component: backend
spec:
  selector:
    app: intelligence-service
  ports:
  - port: 8001
    targetPort: 8002
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: intelligence-models-pvc
  namespace: videocopilot
  labels:
    app: intelligence-service
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: intelligence-logs-pvc
  namespace: videocopilot
  labels:
    app: intelligence-service
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path