apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: videocopilot
  labels:
    app: web-app
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
        component: frontend
    spec:
      initContainers:
      - name: migrate-database
        image: videocopilot/web-app:latest
        command: ['sh', '-c', 'npx prisma migrate deploy']
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: videocopilot-secrets
              key: database-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      containers:
      - name: web-app
        image: videocopilot/web-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: videocopilot-secrets
              key: database-url
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: videocopilot-secrets
              key: nextauth-secret
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: videocopilot-secrets
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: videocopilot-secrets
              key: aws-secret-access-key
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: aws-region
        - name: AWS_S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: aws-s3-bucket
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: web-port
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: node-env
        - name: NEXT_TELEMETRY_DISABLED
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: next-telemetry-disabled
        - name: SESSION_MAX_AGE
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: session-max-age
        - name: SESSION_UPDATE_AGE
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: session-update-age
        - name: RATE_LIMIT_MAX
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: rate-limit-max
        - name: RATE_LIMIT_WINDOW
          valueFrom:
            configMapKeyRef:
              name: videocopilot-config
              key: rate-limit-window
        - name: VIDEO_PROCESSING_SERVICE_URL
          value: "http://video-processing-service:8002"
        - name: INTELLIGENCE_SERVICE_URL
          value: "http://intelligence-service:8001"
        - name: EMBEDDING_SERVICE_URL
          value: "http://embedding-service:8000"
        - name: NEXTAUTH_URL
          value: "https://videocopilot.yourdomain.com"  # Update with your domain
        volumeMounts:
        - name: logs-storage
          mountPath: /app/logs
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: logs-storage
        persistentVolumeClaim:
          claimName: web-app-logs-pvc
      imagePullSecrets:
      - name: docker-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: videocopilot
  labels:
    app: web-app
    component: frontend
spec:
  selector:
    app: web-app
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-app-logs-pvc
  namespace: videocopilot
  labels:
    app: web-app
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path