# web-app/Dockerfile

# --- Build Stage ---
FROM node:20-bullseye AS builder
WORKDIR /app

# Install dependencies
COPY package*.json prisma ./
RUN npm ci

# Copy rest of code
COPY . .

# Generate Prisma client
RUN npx prisma generate

# Build Next.js
RUN npm run build

# --- Production Stage ---
FROM node:20-bullseye-slim
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000

# Copy built files and deps
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/prisma ./prisma

EXPOSE 3000
CMD ["npm", "run","start"]