pipeline {
  agent any

  environment {
    APP_NAME = "videocopilot-web-app"
    IMAGE_NAME = "ghcr.io/jaidityayadav/${APP_NAME}:latest"
    CONTAINER_NAME = "videocopilot_web"
    PORT = "3000"
    ENV_FILE = "/home/ec2-user/VideoCopilot/web-app/.env"
  }

  stages {
    stage('Pull Image') {
      steps {
        withCredentials([string(credentialsId: 'ghcr-token', variable: 'GHCR_TOKEN')]) {
          sh 'echo $GHCR_TOKEN | docker login ghcr.io -u jaidityayadav --password-stdin'
        }
        sh "docker pull ${IMAGE_NAME}"
      }
    }

    stage('Deploy Container') {
      steps {
        sh """
          docker rm -f ${CONTAINER_NAME} || true
          docker run -d \
            --name ${CONTAINER_NAME} \
            -p ${PORT}:3000 \
            --env-file ${ENV_FILE} \
            ${IMAGE_NAME}
        """
      }
    }
  }

  post {
    success {
      echo "Deployment successful!"
    }
    failure {
      echo "Deployment failed."
    }
  }
}
