pipeline {
  agent any

  environment {
    APP_NAME = "videocopilot-web-app"
    IMAGE_NAME = "ghcr.io/jaidityayadav/${APP_NAME}:latest"
    CONTAINER_NAME = "videocopilot_web"
    PORT = "3000"
    ENV_FILE = "/home/ec2-user/VideoCopilot/web-app/.env"
    SSH_KEY_ID = "git" // Jenkins credential ID
  }

  stages {
    stage('Checkout via SSH') {
      steps {
        sshagent([env.SSH_KEY_ID]) {
          sh 'git clone git@github.com:jaidityayadav/VideoCopilot.git'
        }
      }
    }

    stage('Pull Image') {
      steps {
        sh "docker pull ${IMAGE_NAME}"
      }
    }

    stage('Deploy Container') {
      steps {
        sh """
          docker rm -f ${CONTAINER_NAME} || true
          docker run -d \
            --name ${CONTAINER_NAME} \
            -p ${PORT}:3000 \
            --env-file ${ENV_FILE} \
            ${IMAGE_NAME}
        """
      }
    }
  }

  post {
    success {
      echo "Deployment successful!"
    }
    failure {
      echo "Deployment failed."
    }
  }
}
