#!/usr/bin/env tsx

import { execSync } from 'child_process';
import path from 'path';
import fs from 'fs';

console.log('🚀 Generating TypeScript types from Prisma schema...');

// Get current directory
const __dirname = path.dirname(new URL(import.meta.url).pathname);

try {
  // Generate Prisma client
  execSync('prisma generate --schema=schema/schema.prisma', {
    stdio: 'inherit',
    cwd: path.join(__dirname, '..')
  });

  // Create index file to export all types
  const indexContent = `
// Generated TypeScript types from Prisma schema
// This file is automatically generated - do not edit manually

export * from './client';

// Generated at: ${new Date().toISOString()}
`.trim();

  const outputDir = path.join(__dirname, '../generated/typescript');
  fs.writeFileSync(path.join(outputDir, 'index.ts'), indexContent);

  console.log('✅ TypeScript types generated successfully!');
  console.log('📁 Output location: generated/typescript/');

} catch (error) {
  console.error('❌ Error generating TypeScript types:', error instanceof Error ? error.message : String(error));
  throw error;
}