apiVersion: apps/v1
kind: Deployment
metadata:
  name: intelligence-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intelligence-service
  template:
    metadata:
      labels:
        app: intelligence-service
    spec:
      containers:
        - name: intelligence-service
          image: ghcr.io/jaidityayadav/intelligence-service:latest
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          ports:
            - containerPort: 8002
      imagePullSecrets:
        - name: ghcr
---
apiVersion: v1
kind: Service
metadata:
  name: intelligence-service
spec:
  type: LoadBalancer
  selector:
    app: intelligence-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
