apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-processing-service
  template:
    metadata:
      labels:
        app: video-processing-service
    spec:
      containers:
        - name: video-processing-service
          image: ghcr.io/jaidityayadav/video-processing-service:latest
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: video-processing-service
spec:
  type: LoadBalancer
  selector:
    app: video-processing-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
