#cloud-config

# Set root password and enable password authentication
chpasswd:
  list: |
    root:${root_password}
  expire: false

ssh_pwauth: true

# Configure SSH settings
write_files:
  - path: /etc/ssh/sshd_config.d/99-videocopilot.conf
    content: |
      PasswordAuthentication yes
      PermitRootLogin yes
      PubkeyAuthentication no
      AuthorizedKeysFile .ssh/authorized_keys

users:
  - name: videocopilot
    groups: users,docker
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    passwd: ${root_password}

packages:
  - curl
  - wget
  - git
  - htop
  - unzip
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release

package_update: true
package_upgrade: true

write_files_append:
  - path: /etc/systemd/resolved.conf
    content: |
      [Resolve]
      DNS=8.8.8.8 8.8.4.4
      FallbackDNS=1.1.1.1 1.0.0.1

  - path: /etc/sysctl.d/99-kubernetes.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1

runcmd:
  - systemctl restart sshd
  - swapoff -a
  - sed -i '/swap/d' /etc/fstab
  - sysctl --system
  - mkdir -p /opt/videocopilot/{envs,configs,data,logs}
  - chown -R videocopilot:videocopilot /opt/videocopilot
  - timedatectl set-timezone UTC
  - |
    cat > /etc/logrotate.d/videocopilot << EOF
    /opt/videocopilot/logs/*.log {
        daily
        missingok
        rotate 30
        compress
        notifempty
        sharedscripts
    }
    EOF

final_message: "VideoCopilot droplet initialization complete!"