---
- name: Deploy Environment Files
  hosts: videocopilot
  become: true
  vars_files:
    - vault.yml  # Contains encrypted secrets
  
  tasks:
    - name: Create service environment files
      template:
        src: "{{ item.src }}"
        dest: "/opt/videocopilot/envs/{{ item.dest }}"
        owner: videocopilot
        group: videocopilot
        mode: '0600'
      loop:
        - { src: "embedding-service.env.j2", dest: "embedding-service.env" }
        - { src: "intelligence-service.env.j2", dest: "intelligence-service.env" }
        - { src: "video-processing-service.env.j2", dest: "video-processing-service.env" }
        - { src: "web-app.env.j2", dest: "web-app.env" }

    - name: Create shared configuration files
      template:
        src: "{{ item.src }}"
        dest: "/opt/videocopilot/configs/{{ item.dest }}"
        owner: videocopilot
        group: videocopilot
        mode: '0644'
      loop:
        - { src: "prometheus.yml.j2", dest: "prometheus.yml" }
        - { src: "grafana-datasources.yml.j2", dest: "grafana-datasources.yml" }

    - name: Verify environment files
      stat:
        path: "/opt/videocopilot/envs/{{ item }}"
      register: env_files
      loop:
        - embedding-service.env
        - intelligence-service.env
        - video-processing-service.env
        - web-app.env

    - name: Display environment file status
      debug:
        msg: "Environment file {{ item.item }} exists: {{ item.stat.exists }}"
      loop: "{{ env_files.results }}"