---
- hosts: servers
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Install k3s (lightweight Kubernetes) with public IP SAN
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--tls-san {{ ansible_host }}" sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Copy k3s kubeconfig to user home
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/ec2-user/k3s.yaml
        owner: ec2-user
        group: ec2-user
        mode: '0644'
        remote_src: yes
      become: yes

    - name: Fetch kubeconfig to local machine
      fetch:
        src: /home/ec2-user/k3s.yaml
        dest: ./k3s.yaml
        flat: yes

    # To deploy your Docker images, add tasks here to apply your manifests or Helm charts
    # - name: Deploy app with kubectl or helm
    #   shell: |
    #     kubectl apply -f /path/to/your/manifest.yaml
    #   args:
    #     chdir: /path/to/your/manifests