name: Build and Push Docker Images

on:
  push:
    branches: [ main, review2, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        service: [web-app, embedding-service, intelligence-service, video-processing-service]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.service }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./${{ matrix.service }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  trigger-jenkins:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/review2'
    
    steps:
    - name: Trigger Jenkins Pipeline
      run: |
        echo "🚀 Images built successfully!"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
        echo "Repository: ${{ github.repository }}"
        echo ""
        echo "📋 Built images:"
        echo "  - ghcr.io/${{ github.repository }}/web-app:${{ github.ref_name }}"
        echo "  - ghcr.io/${{ github.repository }}/embedding-service:${{ github.ref_name }}"
        echo "  - ghcr.io/${{ github.repository }}/intelligence-service:${{ github.ref_name }}"
        echo "  - ghcr.io/${{ github.repository }}/video-processing-service:${{ github.ref_name }}"
        echo ""
        echo "🔔 Jenkins webhook will be triggered once Jenkins is deployed"
        # Uncomment and configure when Jenkins is ready:
        # curl -X POST "${{ secrets.JENKINS_WEBHOOK_URL }}" \
        #   -H "Authorization: Bearer ${{ secrets.JENKINS_API_TOKEN }}" \
        #   -H "Content-Type: application/json" \
        #   -d '{
        #     "branch": "${{ github.ref_name }}",
        #     "commit": "${{ github.sha }}",
        #     "repository": "${{ github.repository }}"
        #   }'